### ISSUE TITLE
Give script templates access to their own name and other metadata

### ISSUE THREAD

**Issue by anthonyrisinger** [coryb/kingpeon#2]
You can access `options` and `args` via function ([kingpeon.go#L68](https://github.com/coryb/kingpeon/blob/master/kingpeon.go#L68)) but there is no way for a script template to discover the command that triggered it, or other useful information.

This package is used by [go-jira](https://github.com/Netflix-Skunkworks/go-jira). I'm trying to make a common entry point like so:

```yaml
custom-commands:
  - name: sync
    options: ...
    args: ...
    script: |
      JIRA={{jira}} exec {{jira}}-lib sync 10<<'EOF'
      {{toJson options}}
      {{toJson args}}
      EOF
```

The script is the same for every custom command except for the word `sync` (or whatever command is in play) because I don't see a way to get that info, eg. `{{.name}}`.

Could we assign `.` to the config so things like `.name` or `.help` work? Or something else?

Adding `toJson` and `fromJson` would be great too. The heredoc nonsense above is because `go-jira` does not compact the JSON. Lastly, a `shellquote` function would be massively appreciated!
